task: "object_detection"  # Options: "pose", "hand"
input_path: "D:\\youtube\\skiathos-sep 2025\\cats\\cat_20250910_163543016.mp4" 
output_dir: ./results
output_name: "cats.mp4"
frames_dir: ./frames
frame_colour: "white"
labels: ["cat"]

